/*******************************************************************************
 *
 * File Name: H01indexedCSVdatabase.hpp
 * Author: Richard Bruce Baxter - Copyright (c) 2021 Baxter AI (baxterai.com)
 * License: MIT License
 * Project: H01LocalConnectome
 * Requirements: BAI SHARED C++ library, Eigen 3 C++ library
 * Compilation: ./compileH01indexedCSVdatabase.sh
 * Usage: ./H01indexedCSVdatabase.exe
 * Description: H01 indexed CSV database (global defs)
 * Comments:
 * /
 *******************************************************************************/

#ifndef HEADER_H01indexedCSVdatabase
#define HEADER_H01indexedCSVdatabase

#include "SHAREDglobalDefs.hpp"

extern string currentDirectory;

//execution modes:
#define INDEXED_CSV_DATABASE_CREATE	//mode 1 (converts Avro Json C3 Synaptic connections database to indexed CSV database, indexed by pre/postsynaptic neuron ID)
#define INDEXED_CSV_DATABASE_QUERY	//mode 2 (queries indexed CSV database, based on local connectome neuron id list)
#define INDEXED_CSV_DATABASE_VISUALISE_LOCAL_CONNECTOME	//mode 3 (visualises local connectome datasets)	//aka LOCAL_CONNECTOME_CSV_DATASET_VISUALISE
#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME	//mode 4 (traces local connectome dataset, saving visualisation)
//query modes:
#ifdef INDEXED_CSV_DATABASE_QUERY
	#define INDEXED_CSV_DATABASE_QUERY_EXTRACT_INCOMING_OUTGOING_CONNECTIONS	//mode 1 (lookup indexed CSV database by neuron ID, and find incoming/outgoing target connections, and write them to file)
	#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING	//mode 2 (lookup indexed CSV database by neuron ID, find incoming target connections, and generate visualisation)
	#define INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET	//mode 3 (automatically generate localConnectomeConnections-typesFromPresynapticNeurons.csv/localConnectomeConnections-typesFromEMimages.csv from localConnectomeNeurons.csv and H01 indexed CSV database)
	#define INDEXED_CSV_DATABASE_QUERY_COUNT_PROPORTION_LOCAL_VS_NONLOCAL_CONNECTIONS	//mode 4 (lookup indexed CSV database by neuron ID, count/infer proportion of incoming/outgoing excitatory/inhibitory target connections to local vs distal neurons)
	#define INDEXED_CSV_DATABASE_QUERY_COMPLETE_LOCAL_CONNECTOME_CONNECTIONS_DATASET	//mode 5 (lookup indexed CSV database by pre/post synaptic connection neuron ID, and identify connection with post/pre synaptic X/Y coordinates (if type=UNKNOWN), add post/pre synaptic neuron ID, Z coordinates, and type to connection dataset)
#endif

#define EXECUTION_MODE_INDEXED_CSV_DATABASE_CREATE 1
#define EXECUTION_MODE_INDEXED_CSV_DATABASE_QUERY 2
#define EXECUTION_MODE_INDEXED_CSV_DATABASE_VISUALISE_LOCAL_CONNECTOME 3
#define EXECUTION_MODE_INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME 4
#ifdef INDEXED_CSV_DATABASE_QUERY
	#define QUERY_MODE_INDEXED_CSV_DATABASE_QUERY_EXTRACT_INCOMING_OUTGOING_CONNECTIONS 1
	#define QUERY_MODE_INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING 2
	#define QUERY_MODE_INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET	3
	#define QUERY_MODE_INDEXED_CSV_DATABASE_QUERY_COUNT_PROPORTION_LOCAL_VS_NONLOCAL_CONNECTIONS 4
	#define QUERY_MODE_INDEXED_CSV_DATABASE_QUERY_COMPLETE_LOCAL_CONNECTOME_CONNECTIONS_DATASET 5
#endif
#define EXECUTION_MODE_DEFAULT (EXECUTION_MODE_INDEXED_CSV_DATABASE_QUERY) 
#define QUERY_MODE_DEFAULT (QUERY_MODE_INDEXED_CSV_DATABASE_QUERY_COUNT_PROPORTION_LOCAL_VS_NONLOCAL_CONNECTIONS)
#define EXECUTION_MODES_TOTAL (4)
#define QUERY_MODES_TOTAL (5)

#ifdef INDEXED_CSV_DATABASE_VISUALISE_LOCAL_CONNECTOME
	//#define LOCAL_CONNECTOME_VISUALISATION_BACKWARDS_COMPATIBILITY_WITH_ODS_GENERATED_FILES	//temporary for diff comparisons between H01indexedCSVdatabase generated visualisations and ODS generated visualisations (visualisation generation verification)	//slower as uses non-distinct neuron id lists
#endif

//apache avro C3 Synaptic connections database parameters:
#ifdef INDEXED_CSV_DATABASE_CREATE
	//#define INDEXED_CSV_DATABASE_CREATE_DEBUG	//disable this DEBUG parameter to create the database (enabled for safety - prevents overwrite of indexed database; takes ~6 hours to regenerate)
	#define AVRO_JSON_DATABASE_FOLDER "/media/user/large/h01data/data/exported/json"
#endif

//common H01 indexed csv database parameters:
#ifdef INDEXED_CSV_DATABASE_CREATE_DEBUG
	#define INDEXED_CSV_DATABASE_FOLDER "/media/user/large/source/h01Connectome/indexedSVGdatabase/trial/indexedTrial"
#else
	#define INDEXED_CSV_DATABASE_FOLDER "/media/user/ssddata/indexed"
#endif

//common apache avro C3 Synaptic connections database parameters:
#define AVRO_JSON_DATABASE_EXCITATORY_SYNAPSE_TYPE (2)
#define AVRO_JSON_DATABASE_INHIBITORY_SYNAPSE_TYPE (1)
#define AVRO_JSON_DATABASE_COORDINATES_RANGE_X (473357-107342)	//366015
#define AVRO_JSON_DATABASE_COORDINATES_RANGE_Y (282046-45528)	//236518
#define AVRO_JSON_DATABASE_COORDINATES_RANGE_Z (5248-0)	//5248
#define AVRO_JSON_DATABASE_COORDINATES_CALIBRATION_X (1.0)
#define AVRO_JSON_DATABASE_COORDINATES_CALIBRATION_Y (1.0)
#define AVRO_JSON_DATABASE_COORDINATES_CALIBRATION_Z (4.0)	//requires calibration	//can be used to enhance Z axis visibility

//common local connectome dataset parameters:
#define LOCAL_CONNECTOME_FOLDER_BASE_USE_RELATIVE_FOLDER
#ifdef LOCAL_CONNECTOME_FOLDER_BASE_USE_RELATIVE_FOLDER
	#define LOCAL_CONNECTOME_FOLDER_BASE "../"	
#else
	#define LOCAL_CONNECTOME_FOLDER_BASE "/media/user/large/source/h01Connectome/H01LocalConnectome/"	
#endif
#define LOCAL_CONNECTOME_DATASET_FOLDER "datasets/"
#ifdef LOCAL_CONNECTOME_VISUALISATION_BACKWARDS_COMPATIBILITY_WITH_ODS_GENERATED_FILES
	#define LOCAL_CONNECTOME_DATASET_NEURONS_FILENAME "localConnectomeNeurons-nonDistinct.csv"
#else
	#define LOCAL_CONNECTOME_DATASET_NEURONS_FILENAME "localConnectomeNeurons.csv"
#endif
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FILENAME_TYPES_DERIVED_FROM_PRESYNAPTIC_NEURONS "localConnectomeConnections-typesFromPresynapticNeurons.csv"
#ifdef LOCAL_CONNECTOME_VISUALISATION_BACKWARDS_COMPATIBILITY_WITH_ODS_GENERATED_FILES
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FILENAME_TYPES_DERIVED_FROM_EM_IMAGES "localConnectomeConnections-typesFromEMimages-backwardsCompatibilityWithDevODSGenerations.csv"
#else
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FILENAME_TYPES_DERIVED_FROM_EM_IMAGES "localConnectomeConnections-typesFromEMimages.csv"
#endif
#ifdef INDEXED_CSV_DATABASE_QUERY_COMPLETE_LOCAL_CONNECTOME_CONNECTIONS_DATASET
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FILENAME_TYPES_DERIVED_FROM_EM_IMAGES_USEALLVALUESAVAILABLEFROMINBODYCELLCONNECTION "localConnectomeConnections-typesFromEMimages-useAllValuesAvailableFromInBodyCellConnection.csv"
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FILENAME_TYPES_DERIVED_FROM_EM_IMAGES_UNKNOWN_NEURON_ID "0"
#endif

#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_NEURON_ID (0)	//C3 database neuron_id
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_X (1)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_Y (2)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_Z (3)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_TYPE (4)	//C3 database neuron classification (PYRAMIDAL, INTERNEURON)
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_EXCITATION_TYPE (5)	//excitatory (1), inhibitory (0)	//derived from neuron type
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_EXCITATION_TYPE_EXCITATORY (1)
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_EXCITATION_TYPE_INHIBITORY (0)
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_EXCITATION_TYPE_UNKNOWN (-1)
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_TYPE_PYRAMIDAL "PYRAMIDAL"
#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_TYPE_INTERNEURON "INTERNEURON"
//#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_TYPE_UNKNOWN "UNKNOWN"	//not used in current local connectome dataset (localConnectomeNeurons.csv)
#define LOCAL_CONNECTOME_DATASET_NEURONS_HEADER "id,x,y,z,type,excitation_type"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_PRE_ID (0)	//C3 database neuron_id
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_PRE_X (1)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_PRE_Y (2)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_PRE_Z (3)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_PRE_TYPE (4)	//C3 database neuron classification (PYRAMIDAL, INTERNEURON)
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_ID (5)	//C3 database neuron_id
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_X (6)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_Y (7)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_Z (8)	//C3 database neuron centroid coordinates
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_TYPE (9)	//C3 database neuron classification (PYRAMIDAL, INTERNEURON)
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_CLASS (10)	//C3 database synapse connection site (DENDRITE, SOMA, UNKNOWN) //not used
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_SYN_NUM (11)	//number of connections
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_EXCITATION_TYPE (12)	//excitatory (1), inhibitory (0)	//derived from neuron type [connectionTypesDerivedFromEMimages] or C3 connections database [connectionTypesDerivedFromPresynapticNeurons]
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_EXCITATION_TYPE_EXCITATORY (1)
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_EXCITATION_TYPE_INHIBITORY (0)
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_EXCITATION_TYPE_UNKNOWN (-1)	//is this required?
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_TYPE_PYRAMIDAL "PYRAMIDAL"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_TYPE_INTERNEURON "INTERNEURON"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_TYPE_UNKNOWN "UNKNOWN"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_CLASS_LABEL_DENDRITE "DENDRITE"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_CLASS_LABEL_SOMA "SOMA"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_CLASS_LABEL_UNKNOWN "UNKNOWN"
#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_HEADER "pre_id,pre_x,pre_y,pre_z,pre_type,post_id,post_x,post_y,post_z,post_type,post_class_label,syn_num,excitation_type"



//common H01 indexed csv database parameters:
#define AVRO_JSON_DATABASE_NEURON_ID_MAX_NUM_CHARACTERS (11)
#define INDEXED_CSV_DATABASE_STORE_MULTIPLE_PREPOSTSYNAPTIC_NEURONID_SYNAPSES_PER_FILE	//reduces number of files, requires further searching of files by application reading indexed csv database
#ifdef INDEXED_CSV_DATABASE_STORE_MULTIPLE_PREPOSTSYNAPTIC_NEURONID_SYNAPSES_PER_FILE
//eg 123/rawPre|PostSynapticNeuronID123.json|csv
#define INDEXED_CSV_DATABASE_NUMBER_LEVELS (2)
#define INDEXED_CSV_DATABASE_NUMBER_CHARACTERS_PER_FOLDER_LEVEL (3)
#define INDEXED_CSV_DATABASE_FILENAME_NEURONID_MAX_NUM_CHARACTERS (6)	//must be greater than (INDEXED_CSV_DATABASE_NUMBER_LEVELS-1)*INDEXED_CSV_DATABASE_NUMBER_CHARACTERS_PER_FOLDER_LEVEL
#else
//eg 1234/5678/rawPre|PostSynapticNeuronID123456789AB.json|csv
#define INDEXED_CSV_DATABASE_NUMBER_LEVELS (3)
#define INDEXED_CSV_DATABASE_NUMBER_CHARACTERS_PER_FOLDER_LEVEL (4)
#define INDEXED_CSV_DATABASE_FILENAME_NEURONID_MAX_NUM_CHARACTERS (AVRO_JSON_DATABASE_NEURON_ID_MAX_NUM_CHARACTERS)
#endif
#define INDEXED_CSV_DATABASE_FILENAME_PREFIX_PRESYNAPTIC_CSV "csvPreSynapticNeuronID"
#define INDEXED_CSV_DATABASE_FILENAME_PREFIX_PRESYNAPTIC_RAW "rawPreSynapticNeuronID"
#define INDEXED_CSV_DATABASE_FILENAME_PREFIX_POSTSYNAPTIC_CSV "csvPostSynapticNeuronID"
#define INDEXED_CSV_DATABASE_FILENAME_PREFIX_POSTSYNAPTIC_RAW "rawPostSynapticNeuronID"
#define INDEXED_CSV_DATABASE_PRESYNAPTIC_SITE_NEURON_ID_FIELD_INDEX (0)
#define INDEXED_CSV_DATABASE_POSTSYNAPTIC_SITE_NEURON_ID_FIELD_INDEX (1)
#define INDEXED_CSV_DATABASE_PRESYNAPTIC_SITE_TYPE_FIELD_INDEX (2)
#define INDEXED_CSV_DATABASE_POSTSYNAPTIC_SITE_TYPE_FIELD_INDEX (3)
#define INDEXED_CSV_DATABASE_PRESYNAPTIC_SITE_CLASSLABEL_FIELD_INDEX (4)
#define INDEXED_CSV_DATABASE_POSTSYNAPTIC_SITE_CLASSLABEL_FIELD_INDEX (5)
#define INDEXED_CSV_DATABASE_PRESYNAPTIC_SITE_BASENEURON_ID_FIELD_INDEX (6)
#define INDEXED_CSV_DATABASE_POSTSYNAPTIC_SITE_BASENEURON_ID_FIELD_INDEX (7)
#define INDEXED_CSV_DATABASE_SYNAPSE_LOCATION_COORDINATE_X_FIELD_INDEX (8)
#define INDEXED_CSV_DATABASE_SYNAPSE_LOCATION_COORDINATE_Y_FIELD_INDEX (9)
#define INDEXED_CSV_DATABASE_SYNAPSE_LOCATION_COORDINATE_Z_FIELD_INDEX (10)
#define INDEXED_CSV_DATABASE_SYNAPSE_TYPE_FIELD_INDEX (11)
#define INDEXED_CSV_DATABASE_NUMBER_FIELDS (12)


//common file format parameters:
#define LDR_REFERENCE_TYPE_SUBREFERENCE (1)
#define LDR_REFERENCE_TYPE_LINE (2)
#define LDR_REFERENCE_TYPE_TRIANGLE (3)
#define LDR_REFERENCE_TYPE_QUADRILATERAL (4)
#define JSON_FILE_EXTENSION ".json"
#define CSV_FILE_EXTENSION  ".csv"
#define LDR_FILE_EXTENSION  ".ldr"
#define SVG_FILE_EXTENSION  ".svg"
#define CSV_DELIMITER ","
#define CSV_DELIMITER_CHAR ','
#define LDR_DELIMITER " "



//mode INDEXED_CSV_DATABASE_CREATE parameters:
#ifdef INDEXED_CSV_DATABASE_CREATE
	//apache avro C3 Synaptic connections database parameters:
	#define MAX_SSD_SIZE	//impose database size limit (50GB)
	#ifdef MAX_SSD_SIZE
		#define EXECUTE_SUBSET
		#define AVRO_JSON_DATABASE_FILEINDEX_START (0)
		#define AVRO_JSON_DATABASE_FILEINDEX_END (165)
	#else
		#define AVRO_JSON_DATABASE_FILEINDEX_START (0)
		#define AVRO_JSON_DATABASE_FILEINDEX_END (165)
		#define SAVE_RAW_JSON	//unrestricted by size 
	#endif

	#ifdef INDEXED_CSV_DATABASE_CREATE_DEBUG
		#define AVRO_JSON_DATABASE_FILEINDEX_START (0)
		#define AVRO_JSON_DATABASE_FILEINDEX_END (0)
	#endif
	//#define DEBUG_RESTART
	#ifdef DEBUG_RESTART
		#define AVRO_JSON_DATABASE_FILEINDEX_START (0)
		#define AVRO_JSON_DATABASE_FILEINDEX_END (0)
		#define DEBUG_RESTART_LINEINDEX_START (620306) //614124
	#endif
#endif

//mode INDEXED_CSV_DATABASE_QUERY parameters:
#ifdef INDEXED_CSV_DATABASE_QUERY
	
	#define INDEXED_CSV_DATABASE_QUERY_PREFER_DATASET_LOCAL_CONNECTOME_NEURONS
	#ifdef INDEXED_CSV_DATABASE_QUERY_PREFER_DATASET_LOCAL_CONNECTOME_NEURONS
		//always read neuron lists from local connectome dataset ("localConnectomeNeurons.csv")
		#define INDEXED_CSV_DATABASE_QUERY_PREFER_DATASET_LOCAL_CONNECTOME_NEURONS_VALUE true
		#define INDEXED_CSV_DATABASE_QUERY_READ_DATASET_LOCAL_CONNECTOME_NEURONS	//localConnectomeNeurons.csv derived from in_body_cell_connection.csv - pre/postsynaptic distinct neuron ids
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST_DISTINCT_FILE_NAME (LOCAL_CONNECTOME_DATASET_NEURONS_FILENAME)
	#else
		//read neuron lists from separate file if possible ("localConnectomeNeuronIDlistDistinct.csv")
		#define INDEXED_CSV_DATABASE_QUERY_PREFER_DATASET_LOCAL_CONNECTOME_NEURONS_VALUE false
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST_DISTINCT_FILE_NAME "localConnectomeNeuronIDlistDistinct.csv"	//from in_body_cell_connection.csv - pre/postsynaptic distinct neuron ids		
	#endif
	
	//mode INDEXED_CSV_DATABASE_QUERY_EXTRACT_INCOMING_OUTGOING_CONNECTIONS parameters:
	#ifdef INDEXED_CSV_DATABASE_QUERY_EXTRACT_INCOMING_OUTGOING_CONNECTIONS
		#define INDEXED_CSV_DATABASE_QUERY_OUTPUT	//mandatory

		//input:
		//see above
		
		/*	
		//depreciated;
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST1_FILE_NAME "localConnectomeNeuronIDlist1.csv"	//from in_body_cell_connection.csv - presynaptic neuron ids
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST2_FILE_NAME "localConnectomeNeuronIDlist2.csv"	//from in_body_cell_connection.csv - postsynaptic neuron ids
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST1_CONNECTIONS_PRESYNAPTIC_FILE_NAME "localConnectomeNeuronIDlist1connectionsPresynaptic.csv"
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST1_CONNECTIONS_POSTSYNAPTIC_FILE_NAME "localConnectomeNeuronIDlist1connectionsPostsynaptic.csv"
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST2_CONNECTIONS_PRESYNAPTIC_FILE_NAME "localConnectomeNeuronIDlist2connectionsPresynaptic.csv"
		#define INDEXED_CSV_DATABASE_QUERY_NEURON_LIST2_CONNECTIONS_POSTSYNAPTIC_FILE_NAME "localConnectomeNeuronIDlist2connectionsPostsynaptic.csv"
		*/
		//output:
		#define INDEXED_CSV_DATABASE_QUERY_WRITE_CURRENT_FOLDER
		#define INDEXED_CSV_DATABASE_QUERY_EXTRACT_INCOMING_OUTGOING_CONNECTIONS_NEURON_LIST_CONNECTIONS_PRESYNAPTIC_FILE_NAME "localConnectomeNeuronIDlistConnectionsPresynaptic.csv"
		#define INDEXED_CSV_DATABASE_QUERY_EXTRACT_INCOMING_OUTGOING_CONNECTIONS_NEURON_LIST_CONNECTIONS_POSTSYNAPTIC_FILE_NAME "localConnectomeNeuronIDlistConnectionsPostsynaptic.csv"
	#endif
	
	//mode INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING parameters:
	#ifdef INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING
		
		//input:
		//see above

		#define INDEXED_CSV_DATABASE_ALGORITHMS
		#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_MIN_NUM_POINTS_REQUIRED (20)	//(2)
		#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_NON_LOCAL_NEURONS_REQUIRED
		#ifdef INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_NON_LOCAL_NEURONS_REQUIRED
			#define INDEXED_CSV_DATABASE_QUERY_EFFICIENT_STORE_NEURON_IDS_IN_MAP
		#endif
		#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_EST_TYPE_BY_AVERAGE_SYNAPSE_TYPE
		#ifdef INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_EST_TYPE_BY_AVERAGE_SYNAPSE_TYPE
			#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_CONNECTION_TYPE_REQUIRED
			#ifdef INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_CONNECTION_TYPE_REQUIRED
				#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_CONNECTION_TYPE (AVRO_JSON_DATABASE_EXCITATORY_SYNAPSE_TYPE)	//excitatory
			#endif
		#endif
		
		//MANDATORY: INDEXED_CSV_DATABASE_QUERY_GET_LOCATION	//used to perform incoming long range axonal tract position/direction estimation (not just statistical comparison of distal vs local input)
		#define INDEXED_CSV_DATABASE_QUERY_OUTPUT	//mandatory	//performance speed by disabling primary output file write
		#ifdef INDEXED_CSV_DATABASE_QUERY_OUTPUT
			#define INDEXED_CSV_DATABASE_QUERY_OUTPUT_INCOMING_AXON_MAPPING
		#endif
		
		//#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_2D_POLY_REGRESSION
		#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_3D_LINEAR_REGRESSION
		#ifdef INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_3D_LINEAR_REGRESSION
			#define INDEXED_CSV_DATABASE_QUERY_OUTPUT_INCOMING_AXON_MAPPING_LDR
		#else
			#define INDEXED_CSV_DATABASE_QUERY_OUTPUT_INCOMING_AXON_MAPPING_CSV
		#endif
	
		#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_CONNECTION_TYPE_EXCITATORY_COLOUR (SHARED_COLOUR_GREEN)
		#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_CONNECTION_TYPE_INHIBITORY_COLOUR (SHARED_COLOUR_RED)
			
		//output:
		#define INDEXED_CSV_DATABASE_QUERY_WRITE_CURRENT_FOLDER
		#ifdef INDEXED_CSV_DATABASE_QUERY_OUTPUT_INCOMING_AXON_MAPPING_LDR
			#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_FILE_NAME "localConnectomeIncomingAxonMapping.ldr"		
		#else
			#define INDEXED_CSV_DATABASE_QUERY_PERFORM_INCOMING_AXON_MAPPING_FILE_NAME "localConnectomeIncomingAxonMapping.csv"	//"localConnectomeNeuronIDdistinctListconnectionsPresynaptic.csv"	
		#endif
	#endif

	//mode INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET parameters:
	#ifdef INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET
		
		//#define INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET_ORIG
		
		//input:
		#define INDEXED_CSV_DATABASE_QUERY_READ_DATASET_LOCAL_CONNECTOME_NEURONS	//localConnectomeNeurons.csv derived from in_body_cell_connection.csv - pre/postsynaptic distinct neuron ids	

		#define INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET_VERIFICATION	//verify local connectome connections dataset generation vs existing (dev/ODS generated) connections datasets
		
		#define INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET_LOCAL_NEURONS_REQUIRED
		#ifdef INDEXED_CSV_DATABASE_QUERY_GENERATE_LOCAL_CONNECTOME_CONNECTIONS_DATASET_LOCAL_NEURONS_REQUIRED		
			#define INDEXED_CSV_DATABASE_QUERY_EFFICIENT_STORE_NEURON_IDS_IN_MAP
		#endif
		
		//output:
		#define INDEXED_CSV_DATABASE_QUERY_WRITE_CURRENT_FOLDER
		#define INDEXED_CSV_DATABASE_QUERY_OUTPUT	//mandatory
		
	#endif
	
	//mode INDEXED_CSV_DATABASE_QUERY_COUNT_PROPORTION_LOCAL_VS_NONLOCAL_CONNECTIONS parameters:
	#ifdef INDEXED_CSV_DATABASE_QUERY_COUNT_PROPORTION_LOCAL_VS_NONLOCAL_CONNECTIONS
		//input:
		//see above

		#define INDEXED_CSV_DATABASE_QUERY_EFFICIENT_STORE_NEURON_IDS_IN_MAP
	#endif
	
	//mode INDEXED_CSV_DATABASE_QUERY_COMPLETE_LOCAL_CONNECTOME_CONNECTIONS_DATASET parameters:
	#ifdef INDEXED_CSV_DATABASE_QUERY_COMPLETE_LOCAL_CONNECTOME_CONNECTIONS_DATASET
				
		//input:	
				
		//output:
		#define INDEXED_CSV_DATABASE_QUERY_WRITE_CURRENT_FOLDER
		#define INDEXED_CSV_DATABASE_QUERY_OUTPUT	//mandatory
		
	#endif
	
	#ifndef INDEXED_CSV_DATABASE_QUERY_WRITE_CURRENT_FOLDER
		#define INDEXED_CSV_DATABASE_QUERY_OUTPUT_FOLDER "/media/user/large/source/h01Connectome/indexedSVGdatabase/H01indexedCSVdatabaseQueryOutput"
	#endif
	#ifndef INDEXED_CSV_DATABASE_QUERY_READ_DATASET_LOCAL_CONNECTOME_NEURONS
		//#define INDEXED_CSV_DATABASE_QUERY_READ_CURRENT_FOLDER
	#endif
	

	#define INDEXED_CSV_DATABASE_QUERY_READ_WRITE_TO_FILE_OBJECT	//only use this if output folder exists on a different harddrive (not just partition) to indexed CSV database folder
	//max expected file/string size = indexed csv database query output size (neuron_id ~11 bytes + , + type ~1 byte = ~13 bytes) * avg num connections per neuron ID (~2000) * number of neuron IDs in list (~30000) = 13*2000*30000 = ~1GB of RAM if string	
#endif

//mode INDEXED_CSV_DATABASE_VISUALISE_LOCAL_CONNECTOME parameters:
#ifdef INDEXED_CSV_DATABASE_VISUALISE_LOCAL_CONNECTOME
	
	//2D/3D visualisations;
	#define LOCAL_CONNECTOME_VISUALISATION_2D_SVG
	#define LOCAL_CONNECTOME_VISUALISATION_3D_LDR
	#ifdef LOCAL_CONNECTOME_VISUALISATION_3D_LDR
		#define LOCAL_CONNECTOME_VISUALISATION_3D
	#endif
	
	
	//layer calculations;
	#define LOCAL_CONNECTOME_VISUALISATION_LAYERS
	#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
		#define INDEXED_CSV_DATABASE_CALCULATE_NEURON_LAYERS
	#endif
	#ifdef INDEXED_CSV_DATABASE_CALCULATE_NEURON_LAYERS
		#define CORTICAL_LAYER_KEYPOINT_UNAVAILABLE_VALUE 0
		#define CORTICAL_LAYER_NUMBER_OF_LAYERS (7)	//L2toL1 (1), L3toL2 (2), L4toL3 (3), L5toL4 (4), L6toL5 (5), WMtoL6 (6), WM (7)
		#define CORTICAL_LAYER_BOUNDARY_KEYPOINT_TABLE_FILE_NAME "corticalLayersBoundaryKeypoints.csv"	//this dataset has already had its X/Y coordindates calibrated for visualisation (as it was derived from connections_I/E.svg visualisation; see working/calibration/connections_IE-FlattenBezier.svg)
	#endif


	//visualisation folder names;	
	#define LOCAL_CONNECTOME_VISUALISATION_FOLDER "visualisations/"
	#define LOCAL_CONNECTOME_VISUALISATION_FOLDER_CONNECTION_TYPES_DERIVED_FROM_PRESYNAPTIC_NEURONS "connectionTypesFromPresynapticNeurons/"
	#define LOCAL_CONNECTOME_VISUALISATION_FOLDER_CONNECTION_TYPES_DERIVED_FROM_EM_IMAGES "connectionTypesFromEMimages/"
	#define LOCAL_CONNECTOME_VISUALISATION_FOLDER_2D "2D/"
	#define LOCAL_CONNECTOME_VISUALISATION_FOLDER_3D "3D/"
	#define LOCAL_CONNECTOME_VISUALISATION_TEMPLATES_FOLDER "visualisations/templates"
	//visualisation file names;		
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_DIRECTION "connections_IE"
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_DIRECTION_FLOW "connections_IE_flow"
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_DIRECTION_NUMBER_COLOURSETS (2)
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_DIRECTION_FLOW_NUMBER_COLOURSETS (3)
	#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_LAYERED_DIRECTION "connections_IE_layered"
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_LAYERED_DIRECTION_FLOW "connections_IE_layered_flow"
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_LAYERED_DIRECTION_NUMER_COLOURSETS (2)
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_LAYERED_DIRECTION_FLOW_NUMBER_COLOURSETS (2)
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_LAYERED_SPECIFIC_LAYER "_L"
	#endif
	#ifdef LOCAL_CONNECTOME_VISUALISATION_3D
		#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION "connections_IE"
		#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_FLOW "connections_IE_flow"
		#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS (2)
		#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_FLOW_NUMBER_COLOURSETS (1)
		#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
			#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_LAYERED_DIRECTION "connections_IE_layered"
			#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_LAYERED_DIRECTION_FLOW "connections_IE_layered_flow"
			#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_LAYERED_DIRECTION_NUMER_COLOURSETS (2)
			#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_LAYERED_DIRECTION_FLOW_NUMBER_COLOURSETS (1)
			#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_LAYERED_SPECIFIC_LAYER "_L"
		#endif
	#endif
	#define LOCAL_CONNECTOME_VISUALISATION_FILENAME_COLOURSET_PREPEND ""	//_colourset
	
			
	//visualisation template file names;	
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_PART_IMPORT_FILENAME_PREPEND "connections_IE_part"
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_PREPEND "connections_IE"
	#ifdef LOCAL_CONNECTOME_VISUALISATION_3D
		#define LOCAL_CONNECTOME_VISUALISATION_LDR_PART_IMPORT_FILENAME_PREPEND "connections_IE_part"
		#define LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_PREPEND "connections_IE"
	#endif
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_DIRECTION "-Direction"
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_DIRECTION_FLOW "-DirectionFlow"
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_LAYERED_DIRECTION_FLOW "-LayeredDirectionFlow"
	#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_LAYERED_DIRECTION "-LayeredDirection"
	#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_VISUALISATION "-traceVisualisation"	
	#endif
	
	
	//visualisation coloursets (neurons);
	#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_EXCITATORY "exciteNeuron"
	#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_INHIBITORY "inhibitNeuron"
	#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_UNKNOWN "unknownNeuron"
	#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_APPEND "Color"
	#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_LAYER "Layer"	//LayerX
	#endif
	#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE "traceActive"
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE "Highlight"	
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE "Mark"	
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT_EXCITATORY_NEURON LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_EXCITATORY
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT_INHIBITORY_NEURON LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_INHIBITORY
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT_INACTIVE_NEURON LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_HIGHLIGHT LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_UNKNOWN
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK_EXCITATORY_NEURON LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_EXCITATORY
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK_INHIBITORY_NEURON LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_INHIBITORY
		#define LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK_INACTIVE_NEURON LOCAL_CONNECTOME_VISUALISATION_SVG_FILENAME_APPEND_COLOURSET_TRACE_ACTIVE_MARK LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOURSET_REFERENCE_EXCITATION_TYPE_UNKNOWN
	#endif	
	#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_SVG_HEADER_TEXT "     <!-- neurons with excitatory/inhibitory connections -->"
	#ifdef LOCAL_CONNECTOME_VISUALISATION_3D
		#ifdef LOCAL_CONNECTOME_VISUALISATION_BACKWARDS_COMPATIBILITY_WITH_ODS_GENERATED_FILES
			static int local_connectome_visualisation_neurons_colour_excitation_type_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_GREEN,SHARED_COLOUR_LIGHT_GREEN};
			static int local_connectome_visualisation_neurons_colour_excitation_type_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_RED,SHARED_COLOUR_LIGHT_RED};
			static int local_connectome_visualisation_neurons_colour_excitation_type_unknown[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_WHITE,SHARED_COLOUR_WHITE};

		#else
			static int local_connectome_visualisation_neurons_colour_excitation_type_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_YELLOW,SHARED_COLOUR_LIGHT_GREEN};
			static int local_connectome_visualisation_neurons_colour_excitation_type_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_MAGENTA,SHARED_COLOUR_LIGHT_RED};
			static int local_connectome_visualisation_neurons_colour_excitation_type_unknown[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_WHITE,SHARED_COLOUR_WHITE};
		#endif
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_LDR_REFERENCE_TYPE (LDR_REFERENCE_TYPE_SUBREFERENCE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_LDR_MODEL_TRANSFORMATION_MATRIX "1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0"
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_LDR_MODEL_FILE_NAME "4-4CUBE.DAT"	//4-4SPHE.DAT
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_LDR_HEADER_TEXT "0 postSynapticNeuronLDRcontent"
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER1 (SHARED_COLOUR_BLUE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER2 (SHARED_COLOUR_RED)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER3 (SHARED_COLOUR_YELLOW)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER4 (SHARED_COLOUR_CYAN)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER5 (SHARED_COLOUR_MAGENTA)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER6 (SHARED_COLOUR_ORANGE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_EXCITENEURON_LAYER7 (SHARED_COLOUR_GREEN)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER1 (SHARED_COLOUR_DARKBLUE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER2 (SHARED_COLOUR_DARKRED)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER3 (SHARED_COLOUR_DARKYELLOW)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER4 (SHARED_COLOUR_AQUA)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER5 (SHARED_COLOUR_PURPLE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER6 (SHARED_COLOUR_BROWN)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_INHIBITNEURON_LAYER7 (SHARED_COLOUR_DARKGREEN)
		/*
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER1 (SHARED_COLOUR_WHITE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER2 (SHARED_COLOUR_WHITE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER3 (SHARED_COLOUR_WHITE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER4 (SHARED_COLOUR_WHITE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER5 (SHARED_COLOUR_WHITE)
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER6 (SHARED_COLOUR_WHITE
		#define LOCAL_CONNECTOME_VISUALISATION_NEURONS_COLOUR_UNKNOWNNEURON_LAYER7 (SHARED_COLOUR_WHITE)
		*/
	#endif
	#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
		#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_ARTIFICIAL_LAYER (6)	//dynamically pregenerated once and saved for efficiency
	#endif
	#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME
		#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_ARTIFICIAL_TRACE (7)	//dynamically pregenerated once and saved for efficiency
		#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_ARTIFICIAL_TRACE_HIGHLIGHT (8)	//dynamically pregenerated once and saved for efficiency
		#define LOCAL_CONNECTOME_DATASET_NEURONS_FIELD_INDEX_ARTIFICIAL_TRACE_MARK (9)	//dynamically pregenerated once and saved for efficiency
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_VALUE_INACTIVE (0)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_VALUE_SOURCE (1)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_VALUE_TARGET (2)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_HIGHLIGHT_VALUE_INACTIVE (0)		
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_HIGHLIGHT_VALUE_INHIBITORY (1)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_HIGHLIGHT_VALUE_EXCITATORY (2)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_MARK_VALUE_INACTIVE (0)		
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_MARK_VALUE_INHIBITORY (1)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_NEURON_TRACE_MARK_VALUE_EXCITATORY (2)	
		static int local_connectome_visualisation_neurons_colour_trace_highlight_value_inactive[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_DARKGREY,SHARED_COLOUR_DARKGREY};	
		static int local_connectome_visualisation_neurons_colour_trace_highlight_value_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_ORANGE,SHARED_COLOUR_LIGHT_RED};
		static int local_connectome_visualisation_neurons_colour_trace_highlight_value_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_DARKBLUE,SHARED_COLOUR_LIGHT_GREEN};
		static int local_connectome_visualisation_neurons_colour_trace_mark_value_inactive[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_WHITE,SHARED_COLOUR_WHITE};	
		static int local_connectome_visualisation_neurons_colour_trace_mark_value_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_YELLOW,SHARED_COLOUR_YELLOW};	
		static int local_connectome_visualisation_neurons_colour_trace_mark_value_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_BLUE,SHARED_COLOUR_BLUE};			
	#endif
		
		
	//visualisation coloursets (connections);
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_EXCITATION_TYPE_EXCITATORY "exciteConnection"
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_EXCITATION_TYPE_INHIBITORY "inhibitConnection"
	#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_LAYER "Layer"	//LayerX
	#endif
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_RADIALGRADIENT_TYPE_POSITIVE (0)    //radial gradient: SVG pre/post synaptic X coordinates drawn left to right
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_RADIALGRADIENT_TYPE_NEGATIVE (1)    //radial gradient: SVG pre/post synaptic X coordinates drawn right to left (requires colour gradient switch)
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_RADIALGRADIENT_TYPE_POSITIVE "RadialGradient2"
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_RADIALGRADIENT_TYPE_NEGATIVE "RadialGradient1"
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_FLOW_TYPE_POSITIVE (1)    //flow: from layer 1->7
	#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_FLOW_TYPE_NEGATIVE (0)    //flow: from layer 7->1
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_FLOW_TYPE_POSITIVE "FlowDirection1"
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_FLOW_TYPE_NEGATIVE "FlowDirection2"  
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_SVG_HEADER_TEXT "   	<!-- excitatory/inhibitory connections -->"
	#ifdef LOCAL_CONNECTOME_VISUALISATION_3D
		static int local_connectome_visualisation_connections_colour_excitation_type_unknown[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_WHITE,SHARED_COLOUR_WHITE};
		static int local_connectome_visualisation_connections_colour_excitation_type_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_GREEN,SHARED_COLOUR_GREEN};
		static int local_connectome_visualisation_connections_colour_excitation_type_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_RED,SHARED_COLOUR_RED};	
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_LDR_REFERENCE_TYPE (LDR_REFERENCE_TYPE_LINE)
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOUR_EXCITATION_TYPE_EXCITATORY_FLOW_TYPE_POSITIVE (SHARED_COLOUR_GREEN)
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOUR_EXCITATION_TYPE_INHIBITORY_FLOW_TYPE_POSITIVE (SHARED_COLOUR_RED)
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOUR_EXCITATION_TYPE_EXCITATORY_FLOW_TYPE_NEGATIVE (SHARED_COLOUR_BLUE)
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOUR_EXCITATION_TYPE_INHIBITORY_FLOW_TYPE_NEGATIVE (SHARED_COLOUR_MAGENTA)
		#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_LDR_HEADER_TEXT "0 connectionLDRcontent"
	#endif 
	#define LOCAL_CONNECTOME_VISUALISATION_CONNECTIONS_COLOURSET_REFERENCE_APPEND ""
	#ifdef LOCAL_CONNECTOME_VISUALISATION_LAYERS
		#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_PRE_ARTIFICIAL_LAYER (13)	//dynamically pregenerated once and saved for efficiency
		#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_POST_ARTIFICIAL_LAYER (14)	//dynamically pregenerated once and saved for efficiency
	#endif
	#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME
		#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_ARTIFICIAL_TRACE (15)	//dynamically pregenerated once and saved for efficiency
		#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_ARTIFICIAL_TRACE_HIGHLIGHT (16)	//dynamically pregenerated once and saved for efficiency
		#define LOCAL_CONNECTOME_DATASET_CONNECTIONS_FIELD_INDEX_ARTIFICIAL_TRACE_MARK (17)	//dynamically pregenerated once and saved for efficiency
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_VALUE_INACTIVE (0)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_VALUE_ACTIVE (1)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_HIGHLIGHT_VALUE_INACTIVE (0)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_HIGHLIGHT_VALUE_INHIBITORY (1)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_HIGHLIGHT_VALUE_EXCITATORY (2)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_MARK_VALUE_INACTIVE (0)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_MARK_VALUE_INHIBITORY (1)
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_CONNECTION_TRACE_MARK_VALUE_EXCITATORY (2)
		static int local_connectome_visualisation_connections_colour_trace_highlight_value_inactive[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_DARKGREY,SHARED_COLOUR_DARKGREY};
		static int local_connectome_visualisation_connections_colour_trace_highlight_value_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_YELLOW,SHARED_COLOUR_GREEN};
		static int local_connectome_visualisation_connections_colour_trace_highlight_value_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_MAGENTA,SHARED_COLOUR_RED};
		static int local_connectome_visualisation_connections_colour_trace_mark_value_inactive[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_WHITE,SHARED_COLOUR_WHITE};
		static int local_connectome_visualisation_connections_colour_trace_mark_value_excitatory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_YELLOW,SHARED_COLOUR_YELLOW};
		static int local_connectome_visualisation_connections_colour_trace_mark_value_inhibitory[LOCAL_CONNECTOME_VISUALISATION_LDR_FILENAME_DIRECTION_NUMBER_COLOURSETS] = {SHARED_COLOUR_MAGENTA,SHARED_COLOUR_MAGENTA};
	#endif
				
	
	//calibration values extracted from dev/working/calibration/readme.txt - conversion from C3/CSV database to SVG/LDR visualisation:		
	#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_FACTOR_X (0.00744)
	#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_FACTOR_Y (0.00744)
	#ifdef LOCAL_CONNECTOME_VISUALISATION_BACKWARDS_COMPATIBILITY_WITH_ODS_GENERATED_FILES
		#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_FACTOR_Z (0.00744)
	#else
		#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_FACTOR_Z (0.00744*AVRO_JSON_DATABASE_COORDINATES_CALIBRATION_Z)	//requires calibration	//can be used to enhance Z axis visibility
	#endif
	#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_MIN_X (576)	
	#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_MIN_Y (1176.48)
	#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_MIN_Z (0)
	#define LOCAL_CONNECTOME_VISUALISATION_CALIBRATION_DOUBLE_PRECISION (5)	//based on connections_I/E.svg precision

	//flow vectors;
	#define LOCAL_CONNECTOME_VISUALISATION_POSITIVE_FLOW_VECTOR_X (-(3471.18672 - 1925.47464))	//(L1->L6)
	#define LOCAL_CONNECTOME_VISUALISATION_POSITIVE_FLOW_VECTOR_Y (-(2069.5776 - 2837.22192))	//(L1->L6)	
#endif

//mode INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME parameters:
#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME
	
	#define INDEXED_CSV_DATABASE_TRACE_START_LAYER_INDEX (4)	//cortex entry layer index (primary incoming connections from thalamus/cortex)
	
	#define INDEXED_CSV_DATABASE_TRACE_INDEX_PREPEND "TraceIndex"
	
	//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_EMULATE_PUBLICATION_INFORMATION_FLOW_THROUGH_THE_H01_NETWORK	//optional
	#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_EMULATE_PUBLICATION_INFORMATION_FLOW_THROUGH_THE_H01_NETWORK
		//use colourset direction2
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_MAX_NUMBER_ITERATIONS (20)	//20
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB	//perform visualisation subiteration (draw/marks/highlights of neurons/connection)
		#ifdef INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB
			#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB_CONNECTION_SOURCES	//additional visualisation stage useful for clarity (not in original)
			#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB_CONNECTION
			#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB_CONNECTION_TARGETS_OF_INHIBITORY_CONNECTIONS
			#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB_CONNECTION_TARGETS
		#endif
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_TRACE_INHIBITORY_CONNECTIONS
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_DRAW_INHIBITORY_NEURONS
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_DRAW_INHIBITORY_CONNECTIONS
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_HIDE_INACTIVE_NEURONS
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_HIDE_INACTIVE_CONNECTIONS
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_ACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_INACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_ACTIVE_CONNECTIONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_INACTIVE_CONNECTIONS	//optional
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_ACTIVE_NEURONS
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_INACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_ACTIVE_CONNECTIONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_INACTIVE_CONNECTIONS	//optional
	#else
		//use any activated colourset
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_MAX_NUMBER_ITERATIONS (10)	//10
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_SUB	//perform visualisation subiteration (draw/marks/highlights of neurons/connection)
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_TRACE_INHIBITORY_CONNECTIONS
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_DRAW_INHIBITORY_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_DRAW_INHIBITORY_CONNECTIONS
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_HIDE_INACTIVE_NEURONS	//optional
		#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_HIDE_INACTIVE_CONNECTIONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_ACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_INACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_ACTIVE_CONNECTIONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_HIGHLIGHTED_INACTIVE_CONNECTIONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_ACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_INACTIVE_NEURONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_ACTIVE_CONNECTIONS	//optional
		//#define INDEXED_CSV_DATABASE_TRACE_LOCAL_CONNECTOME_COLOUR_MARKED_INACTIVE_CONNECTIONS	//optional
	#endif
			
#endif


#define CPP_STRING_FIND_RESULT_FAIL_VALUE2 int(CPP_STRING_FIND_RESULT_FAIL_VALUE)

#define WRITE_FILE_TRUE (true)
#define WRITE_FILE_FALSE (false)
#define READ_FILE_TRUE (true)
#define READ_FILE_FALSE (false)
#define APPEND_FILE_TRUE (true)
#define APPEND_FILE_FALSE (false)
#define CONNECTION_TYPES_DERIVED_FROM_PRESYNAPTIC_NEURONS (true)
#define CONNECTION_TYPES_DERIVED_FROM_EM_IMAGES (false)
#define QUERY_PRESYNAPTIC_CONNECTION_NEURONS (true)
#define QUERY_POSTSYNAPTIC_CONNECTION_NEURONS (false)
#define LAYER_ENFORCEMENT_TRUE (true)
#define LAYER_ENFORCEMENT_FALSE (false)

#endif
